# Site settings
title: jeremiaspereira.github.io
email: jeremiastpererira@gmail.com
description: 'Front-end Developer, running and biking are my favorite sports, my kindle always accompanies me, lover of simple life thing like cake and coffee.'
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://jeremiaspereira.github.io" # the base hostname & protocol for your site
twitter_username: jerepere
github_username:  jeremiaspereira

# Build settings
markdown: kramdown



