# Site settings
title: jeremiaspereira.github.io
email: jeremiastpererira@gmail.com
description: 'Um mineiro na cidade grande, front-end por amor, vegano por respeito a vida, falando sobre coisas que gosta'
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://jeremiaspereira.github.io" # the base hostname & protocol for your site
twitter_username: jerepere
github_username:  jeremiaspereira

# Build settings
markdown: kramdown



